apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudstrate

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - neo4j.yaml
  - analyst.yaml
  # Uncomment to include scanner job/cronjob
  # - scanner-job.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: cloudstrate

images:
  - name: cloudstrate
    newTag: latest
